### ISSUE TITLE
Layout: cover left sidebar on the right side when too small

### ISSUE THREAD

**Issue by waldyrious** [FontManager/master#50] opened 2018-01-06 12:22 UTC
If the sidebar is resized to be too narrow, the left side of its contents starts sliding out of view (including the "Categories | Collections" buttons at the bottom), which is a quite jarring effect IMO. It would be more intuitive to make the right side be "covered" by the main pane, or perhaps even set a minimum width for the sidebar area (not just its contents) to avoid these overflow issues.

**Comment by JerryCasiano** [comment] 2018-01-06 15:55
Well, "covering" it I think would have the nicest visual effect. But I don't think that would work without some ugly hack involving stacked panes and an overlay.

Setting a minimum width is very easy, however, it also means that you can no longer collapse it completely if you want to which kind of sucks. The other issue with minimum sizes is that the required minimum changes based on things such as system font sizes, language, etc.

So maybe we should set some minimum width but provide a way to open/close the sidebar.

Hmm. I'll have to give this some thought because I still really like the "covering" idea better.

**Comment by waldyrious** [comment] 2018-01-06 19:05
It looks like the inner contents of the sidebar already have a minimum width (perhaps due to the buttons at the bottom?), but the sidebar itself does not; that would explain why the contents start being dragged out of the visible area when the sidebar is resized below a certain width, but before that they get occluded as one would expect. Here are some screenshots that should explain what I mean better than my words:

**Initial state**; everything visible:
<img width="300" src="https://user-images.githubusercontent.com/478237/34642935-8ea8b0a0-f313-11e7-947a-0acd047c1ab7.png"/>
**Correct behavior**; as we start shrinking the sidebar, note how the longer items start being occluded from the right side:
<img width="300" src="https://user-images.githubusercontent.com/478237/34642936-8ec828a4-f313-11e7-96bc-d333e0aea6cd.png"/>
<img width="300" src="https://user-images.githubusercontent.com/478237/34642937-8ee5e8f8-f313-11e7-9406-3c3f361be324.png"/>
<img width="300" src="https://user-images.githubusercontent.com/478237/34642938-8f04b008-f313-11e7-8092-2de90d1c90a6.png"/>
**Incorrect behavior**; This is where shrinking the sidebar further stops covering the contents, and instead starts pushing them out of the window:
<img width="300" src="https://user-images.githubusercontent.com/478237/34642939-8f22c5de-f313-11e7-8eae-775e2fafb399.png"/>
<img width="300" src="https://user-images.githubusercontent.com/478237/34642954-c87e943e-f313-11e7-90ab-d5eee4d82345.png"/>

Would it be possible to remove this minimum size, so that the sidebar could simply continue shrinking and occluding its contents? Maybe changing the minimum size properties of the buttons at the bottom of the sidebar?

**Comment by JerryCasiano** [comment] 2018-01-06 19:42
> Would it be possible to remove this minimum size, so that the sidebar could simply continue shrinking and occluding its contents? Maybe changing the minimum size properties of the buttons at the bottom of the sidebar?

I'll have to double check, but I don't believe we set a minimum size on anything there.
As a said, I avoid setting minimum sizes as much as possible due to the side effects.
I believe the only place we might set minimum size is dialog windows.

To be honest, I think this is more of a toolkit issue (GtkPaned) though I'm not sure it can actually be considered an issue. 
If an area is resizable and a user decides to resize it to a point where it's no longer usable there isn't much that can really be done.

That said, if anybody knows anyway to improve this just using widget properties, I'm all ears. ;-)

**Comment by JerryCasiano** [comment] 2018-01-06 20:03
Another option would be to hide the buttons once it's resized down past a certain point.

**Comment by waldyrious** [comment] 2018-01-06 22:49
> Another option would be to hide the buttons once it's resized down past a certain point.

Sure, but they can still be made to support some squishing if the sidebar is resized. They have plenty of margin and padding at the moment which should be compressible if the available space becomes smaller.

> If an area is resizable and a user decides to resize it to a point where it's no longer usable there isn't much that can really be done aside from the presentation.

Exactly my point: occluding parts of the information by definition makes it invisible and potentially unusable, but the way it's occluded provides hints about what's happening and how it can be handled.

**Comment by JerryCasiano** [comment] 2018-01-07 00:44
> Sure, but they can still be made to support some squishing if the sidebar is resized. 

Yes. But again, this is something that would need to be done at the toolkit level not by the application. 
In other words, that is something that requires changes to GTK+ itself. 

Some applications work around this by setting minimum sizes, but as I said I really don't want to do that because it means you can never completely collapse anything.

This is just the way GtkPaned is designed. It doesn't matter what the content is, it slides out of view it doesn't squish and that's not an option.

### w/o switcher
![screenshot from 2018-01-06 19-28-25](https://user-images.githubusercontent.com/11490124/34645337-4e6d7fca-f318-11e7-9e2a-62fb21c9fd06.png)

You may want to file a request with GTK+ but be prepared for the response that this is working as intended.

**Comment by waldyrious** [comment] 2018-02-22 11:43
Thanks for the extensive responses. At the moment I don't have the headspace to pursue this upstream, but I hope the situation improves in the future for cases like this. Cheers!

**Comment by JerryCasiano** [comment] 2018-06-06 03:54
Accidentally stumbled onto a solution to this issue...

Wrapping a widget in a pane in another pane forces it to stay in place instead of sliding.

I'll include this in the next release.

**Comment by waldyrious** [comment] 2018-06-22 16:59
Oh wow, that's great to hear! I suppose it would make sense to reopen this issue until then, right?

**Comment by JerryCasiano** [comment] 2018-06-22 17:05
Done.

I'm trying to get my current working branch into a decent state at the moment. Soon as I do, it'll be available in a separate testing branch so I can get some feedback on all the changes.

**Comment by JerryCasiano** [comment] 2018-06-27 22:12
This feature is implemented in [testing](https://github.com/FontManager/master/tree/testing)

Please test and provide feedback, if possible.

**Comment by waldyrious** [comment] 2018-06-29 12:03
Do you have any instructions for building from source?

**Comment by JerryCasiano** [comment] 2018-06-29 12:29
Well, I don't know if it'll work right or not but try

    cd build-aux
    make deb

If it still works, it will install the needed dependencies and build a package.

BUT I wouldn't install the package, instead go back up one directory then try to compile again and run it from the build directory.

**Comment by waldyrious** [comment] 2018-06-29 15:13
Looks like it took me a bit further, but not enough:

```
$ cd build-aux
$ make deb

**** Need to ensure build dependencies are installed

sudo apt-get install devscripts equivs
[sudo] password for waldyrious:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  at dctrl-tools debhelper dh-strip-nondeterminism dput libdistro-info-perl libfile-stripnondeterminism-perl libmail-sendmail-perl libsys-hostname-long-perl po-debconf python3-magic wdiff
  ...
Do you want to continue? [Y/n] Y
...
cd /home/waldyrious/.local/src/FontManager && \
mk-build-deps /home/waldyrious/.local/src/FontManager/debian/control && \
sudo dpkg -i /home/waldyrious/.local/src/FontManager/*.deb && rm /home/waldyrious/.local/src/FontManager/*.deb && \
test -e Makefile || ./autogen.sh && \
make dist-bzip2 && \
rm -rf BUILD && \
mkdir BUILD && \
mv font-manager-0.7.4.tar.bz2 BUILD/font-manager_0.7.4.orig.tar.bz2 && \
cd BUILD && \
tar -xvf font-manager_0.7.4.orig.tar.bz2 && \
cp -Rpf ../debian font-manager-0.7.4 && \
cp -pf ../autogen.sh font-manager-0.7.4 && \
cd /home/waldyrious/.local/src/FontManager/BUILD/font-manager-0.7.4 && \
debuild -us -uc && \
cd /home/waldyrious/.local/src/FontManager/build-aux
mk-build-deps: Unable to find package name in control file `/home/waldyrious/.local/src/FontManager/debian/control'
make[1]: Entering directory '/home/waldyrious/.local/src/FontManager/equivs.LXrDdI'
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: building package 'font-manager-build-deps' in '../font-manager-build-deps_0.7.3-1ubuntu1_all.deb'.
make[1]: Leaving directory '/home/waldyrious/.local/src/FontManager/equivs.LXrDdI'

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
Selecting previously unselected package font-manager-build-deps.
(Reading database ... 249647 files and directories currently installed.)
Preparing to unpack .../font-manager-build-deps_0.7.3-1ubuntu1_all.deb ...
Unpacking font-manager-build-deps (0.7.3-1ubuntu1) ...
dpkg: dependency problems prevent configuration of font-manager-build-deps:
 font-manager-build-deps depends on dh-autoreconf; however:
  Package dh-autoreconf is not installed.
 font-manager-build-deps depends on valac (>= 0.24); however:
  Package valac is not installed.
 font-manager-build-deps depends on intltool; however:
  Package intltool is not installed.
 font-manager-build-deps depends on libxml2-dev; however:
  Package libxml2-dev is not installed.
 font-manager-build-deps depends on libfreetype6-dev; however:
  Package libfreetype6-dev is not installed.
 font-manager-build-deps depends on libfontconfig1-dev; however:
  Package libfontconfig1-dev is not installed.
 font-manager-build-deps depends on libglib2.0-dev; however:
  Package libglib2.0-dev is not installed.
 font-manager-build-deps depends on libjson-glib-dev; however:
  Package libjson-glib-dev is not installed.
 font-manager-build-deps depends on libcairo2-dev; however:
  Package libcairo2-dev is not installed.
 font-manager-build-deps depend
dpkg: error processing package font-manager-build-deps (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 font-manager-build-deps
checking for automake >= 1.11.2...
  testing automake... found 1.15
checking for autoreconf >= 2.53...
  testing autoreconf... found 2.69
checking for glib-gettext >= 2.2.0...
  testing glib-gettextize... not found.
***Error***: You must have glib-gettext >= 2.2.0 installed
  to build font-manager.  Download the appropriate package for
  from your distribution or get the source tarball at
    ftp://ftp.gtk.org/pub/gtk/v2.2/glib-2.2.0.tar.gz

Makefile:164: recipe for target 'deb' failed
make: *** [deb] Error 1
```

I suppose I need to manually install all those dependencies listed under the line

    dpkg: dependency problems prevent configuration of font-manager-build-deps

right?

**Comment by waldyrious** [comment] 2018-06-29 15:21
Ok, looks like running `sudo apt install -f` prompted me to install the remaining dependencies; I then went back to the root of the repo and ran `./autogen.sh`, and it did seem to progress some more, but stopped at:

```
checking for GTK... no
configure: error: Package requirements (gtk+-3.0 >= 3.22) were not met:

Requested 'gtk+-3.0 >= 3.22' but version of GTK+ is 3.18.9

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I don't want to mess up my current system (Ubuntu 16.04.4 LTS), especially since I don't normally use it for development. What would you suggest here?

**Comment by JerryCasiano** [comment] 2018-06-29 16:14
Oh jeez.

LTS won't work.

I guess you best bet is to wait for now.

**Comment by waldyrious** [comment] 2018-06-29 20:42
Ok, no problem :)

**Comment by JerryCasiano** [comment] 2018-10-30 06:09
Closing this out because these changes have been merged into master.

The PPA and COPR have been updated.

Unfortunately, I don't believe it builds on anything earlier than Bionic.

**Closed by JerryCasiano** 2018-10-30 06:09 UTC
